version: "1.1.0"
#開発環境
dbuser: "postgres"
dbpassword: "postgres"
dbname: "chat_db"
dbhost: "localhost"
dbport: 5432
sercretkey: "test"
staticpath: "./out"
basepath: "/chat"
environment: 0 #開発環境 -> 0  本番環境 -> 1
